[providers]
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs", "chromium", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "cups", "dbus", "Xdamage", "mesa", "pango", "cairo", "composite", "alsa-lib"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node index.js"